/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HomePage;

import Core.Assessment;
import Core.ReadNLearn;
import com.core.readease.StartingPage;
import java.awt.Color;
import javax.swing.JButton;

/**
 * @author Marc
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                ReadNLearn = new javax.swing.JButton();
                assessmentButton = new javax.swing.JButton();
                backButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new java.awt.GridBagLayout());

                ReadNLearn.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
                ReadNLearn.setText("Read & Learn");
                ReadNLearn.setPreferredSize(new java.awt.Dimension(200, 25));
                ReadNLearn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ReadNLearnMouseClicked(evt);
                        }
                });
                ReadNLearn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadNLearnActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.gridwidth = 2;
                gridBagConstraints.ipadx = 92;
                gridBagConstraints.ipady = 337;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(52, 46, 0, 0);
                getContentPane().add(ReadNLearn, gridBagConstraints);

                assessmentButton.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
                assessmentButton.setText("Assessment");
                assessmentButton.setPreferredSize(new java.awt.Dimension(200, 25));
                assessmentButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                assessmentButtonMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                assessmentButtonMouseExited(evt);
                        }
                });
                assessmentButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                assessmentButtonActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.ipadx = 107;
                gridBagConstraints.ipady = 337;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(52, 11, 0, 69);
                getContentPane().add(assessmentButton, gridBagConstraints);

                backButton.setText("Back");
                backButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                backButtonActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.ipadx = 14;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(18, 46, 37, 0);
                getContentPane().add(backButton, gridBagConstraints);

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void ReadNLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadNLearnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReadNLearnActionPerformed

    private void assessmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assessmentButtonActionPerformed
        // TODO add your handling code here:
        Assessment assessment = new Assessment();
        assessment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assessmentButtonActionPerformed

        private void assessmentButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentButtonMouseEntered
                // TODO add your handling code here:
		assessmentButton.setBackground(Color.LIGHT_GRAY);
        }//GEN-LAST:event_assessmentButtonMouseEntered

        private void assessmentButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentButtonMouseExited
                // TODO add your handling code here:
		assessmentButton.setBackground(new JButton().getBackground());
        }//GEN-LAST:event_assessmentButtonMouseExited

        private void ReadNLearnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReadNLearnMouseClicked
                // TODO add your handling code here:
		ReadNLearn readNLearn = new ReadNLearn();
		readNLearn.setVisible(true);
		this.dispose();
        }//GEN-LAST:event_ReadNLearnMouseClicked

        private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
                // TODO add your handling code here:
		StartingPage startingPage = new StartingPage();
		startingPage.setVisible(true);
		this.dispose();
        }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton ReadNLearn;
        private javax.swing.JButton assessmentButton;
        private javax.swing.JButton backButton;
        // End of variables declaration//GEN-END:variables
}
