/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core;

import Core.Actions.ButtonActions;

import javax.swing.*;

/**
 * @author Marc
 */
public class Assessment extends javax.swing.JFrame {

    private JLabel[] questionLabels;
    private JLabel[] answerLabels;
    private int currentIndex = 0;

    /**
     * Creates new form Assessment2
     */
    public Assessment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                assessmentTabbedPane = new javax.swing.JTabbedPane();
                q1Panel = new javax.swing.JPanel();
                q1Label = new javax.swing.JLabel();
                directionLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                textArea1 = new javax.swing.JTextArea();
                clearButton1 = new javax.swing.JButton();
                readButton1 = new javax.swing.JButton();
                netWordButton1 = new javax.swing.JButton();
                TheWordButton1 = new javax.swing.JButton();
                wetWordButton1 = new javax.swing.JButton();
                isWordButton1 = new javax.swing.JButton();
                nextButton1 = new javax.swing.JButton();
                textToSpeechToggleButton1 = new javax.swing.JToggleButton();
                q2Panel = new javax.swing.JPanel();
                q2Label = new javax.swing.JLabel();
                directionLabel2 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                textArea2 = new javax.swing.JTextArea();
                clearButton2 = new javax.swing.JButton();
                ReadButton2 = new javax.swing.JButton();
                matWordButton2 = new javax.swing.JButton();
                TheWordButton2 = new javax.swing.JButton();
                isWordButton2 = new javax.swing.JButton();
                onWordButton2 = new javax.swing.JButton();
                nextButton2 = new javax.swing.JButton();
                textToSpeechToggleButton2 = new javax.swing.JToggleButton();
                catWordButton2 = new javax.swing.JButton();
                theWordButton2 = new javax.swing.JButton();
                q3Panel = new javax.swing.JPanel();
                q3Label = new javax.swing.JLabel();
                directionLabel3 = new javax.swing.JLabel();
                jScrollPane3 = new javax.swing.JScrollPane();
                textArea3 = new javax.swing.JTextArea();
                clearButton3 = new javax.swing.JButton();
                ReadButton3 = new javax.swing.JButton();
                fishWordButton3 = new javax.swing.JButton();
                TheWordButton3 = new javax.swing.JButton();
                bigWordButton3 = new javax.swing.JButton();
                hasWordButton3 = new javax.swing.JButton();
                nextButton3 = new javax.swing.JButton();
                textToSpeechToggleButton3 = new javax.swing.JToggleButton();
                finsWordButton3 = new javax.swing.JButton();
                q4Panel = new javax.swing.JPanel();
                q4Label = new javax.swing.JLabel();
                directionLabel4 = new javax.swing.JLabel();
                jScrollPane4 = new javax.swing.JScrollPane();
                textArea4 = new javax.swing.JTextArea();
                clearButton4 = new javax.swing.JButton();
                ReadButton4 = new javax.swing.JButton();
                areWordButton4 = new javax.swing.JButton();
                sixWordButton4 = new javax.swing.JButton();
                applesWordButton4 = new javax.swing.JButton();
                ThereWordButton4 = new javax.swing.JButton();
                nextButton4 = new javax.swing.JButton();
                textToSpeechToggleButton4 = new javax.swing.JToggleButton();
                q5Panel = new javax.swing.JPanel();
                q4Label1 = new javax.swing.JLabel();
                directionLabel5 = new javax.swing.JLabel();
                jScrollPane5 = new javax.swing.JScrollPane();
                textArea5 = new javax.swing.JTextArea();
                clearButton5 = new javax.swing.JButton();
                ReadButton5 = new javax.swing.JButton();
                boxWordButton5 = new javax.swing.JButton();
                isWordButton5 = new javax.swing.JButton();
                TheWordButton5 = new javax.swing.JButton();
                theWordButton5 = new javax.swing.JButton();
                nextButton5 = new javax.swing.JButton();
                textToSpeechToggleButton5 = new javax.swing.JToggleButton();
                catWordButton6 = new javax.swing.JButton();
                onWordButton6 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                q1Panel.setBackground(new java.awt.Color(204, 204, 204));

                q1Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q1Label.setForeground(new java.awt.Color(0, 0, 0));
                q1Label.setText("1. What can you say about the net?");

                directionLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel.setText("Direction: Describe the picture using the word");

                textArea1.setBackground(new java.awt.Color(153, 153, 153));
                textArea1.setColumns(20);
                textArea1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea1.setForeground(new java.awt.Color(0, 0, 0));
                textArea1.setRows(5);
                jScrollPane1.setViewportView(textArea1);
                textArea1.setEditable(false);

                clearButton1.setText("Clear");
                clearButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton1ActionPerformed(evt);
                        }
                });

                readButton1.setText("Read");
                readButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButton1ActionPerformed(evt);
                        }
                });

                netWordButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                netWordButton1.setText("net");
                netWordButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                netWordButton1ActionPerformed(evt);
                        }
                });

                TheWordButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                TheWordButton1.setText("The");
                TheWordButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TheWordButton1ActionPerformed(evt);
                        }
                });

                wetWordButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                wetWordButton1.setText("wet");
                wetWordButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                wetWordButton1ActionPerformed(evt);
                        }
                });

                isWordButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                isWordButton1.setText("is");
                isWordButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                isWordButton1ActionPerformed(evt);
                        }
                });

                nextButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton1.setText("Next");
                nextButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton1ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton1.setText("Sound");
                textToSpeechToggleButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout q1PanelLayout = new javax.swing.GroupLayout(q1Panel);
                q1Panel.setLayout(q1PanelLayout);
                q1PanelLayout.setHorizontalGroup(
                        q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q1PanelLayout.createSequentialGroup()
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(q1Label)
                                                        .addComponent(directionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(q1PanelLayout.createSequentialGroup()
                                                                                        .addComponent(wetWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(isWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(q1PanelLayout.createSequentialGroup()
                                                                                        .addComponent(netWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(TheWordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(readButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 34, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q1PanelLayout.createSequentialGroup()
                                                .addGap(0, 667, Short.MAX_VALUE)
                                                .addComponent(textToSpeechToggleButton1))
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(nextButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                q1PanelLayout.setVerticalGroup(
                        q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q1PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textToSpeechToggleButton1)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel)
                                .addGap(12, 12, 12)
                                .addComponent(q1Label)
                                .addGap(18, 18, 18)
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q1PanelLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(clearButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(readButton1))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(netWordButton1)
                                        .addComponent(TheWordButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(wetWordButton1)
                                        .addComponent(isWordButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(nextButton1)
                                .addContainerGap())
                );

                assessmentTabbedPane.addTab("tab1", q1Panel);

                q2Panel.setBackground(new java.awt.Color(204, 204, 204));

                q2Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q2Label.setForeground(new java.awt.Color(0, 0, 0));
                q2Label.setText("2. Where is the Cat?");

                directionLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel2.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel2.setText("Direction: Describe the picture using the word");

                textArea2.setBackground(new java.awt.Color(153, 153, 153));
                textArea2.setColumns(20);
                textArea2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea2.setForeground(new java.awt.Color(0, 0, 0));
                textArea2.setRows(5);
                jScrollPane2.setViewportView(textArea2);
                textArea1.setEditable(false);

                clearButton2.setText("Clear");
                clearButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton2ActionPerformed(evt);
                        }
                });

                ReadButton2.setText("Read");
                ReadButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadButton2ActionPerformed(evt);
                        }
                });

                matWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                matWordButton2.setText("mat");
                matWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                matWordButton2ActionPerformed(evt);
                        }
                });

                TheWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                TheWordButton2.setText("The");
                TheWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TheWordButton2ActionPerformed(evt);
                        }
                });

                isWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                isWordButton2.setText("is");
                isWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                isWordButton2ActionPerformed(evt);
                        }
                });

                onWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                onWordButton2.setText("on");
                onWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                onWordButton2ActionPerformed(evt);
                        }
                });

                nextButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton2.setText("Next");
                nextButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton2ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton2.setText("Sound");
                textToSpeechToggleButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton2ActionPerformed(evt);
                        }
                });

                catWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                catWordButton2.setText("cat");
                catWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                catWordButton2ActionPerformed(evt);
                        }
                });

                theWordButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                theWordButton2.setText("the");
                theWordButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                theWordButton2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout q2PanelLayout = new javax.swing.GroupLayout(q2Panel);
                q2Panel.setLayout(q2PanelLayout);
                q2PanelLayout.setHorizontalGroup(
                        q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q2PanelLayout.createSequentialGroup()
                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(q2Label)
                                                        .addComponent(directionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(q2PanelLayout.createSequentialGroup()
                                                                                        .addComponent(isWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(onWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(q2PanelLayout.createSequentialGroup()
                                                                                        .addComponent(matWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(TheWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                                                .addComponent(catWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(theWordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(clearButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(ReadButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 34, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q2PanelLayout.createSequentialGroup()
                                                .addGap(0, 667, Short.MAX_VALUE)
                                                .addComponent(textToSpeechToggleButton2))
                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(nextButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                q2PanelLayout.setVerticalGroup(
                        q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q2PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textToSpeechToggleButton2)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(q2Label)
                                .addGap(18, 18, 18)
                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q2PanelLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(clearButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ReadButton2))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(matWordButton2)
                                        .addComponent(TheWordButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(isWordButton2)
                                        .addComponent(onWordButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(catWordButton2)
                                        .addComponent(theWordButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(nextButton2)
                                .addContainerGap())
                );

                assessmentTabbedPane.addTab("tab2", q2Panel);

                q3Panel.setBackground(new java.awt.Color(204, 204, 204));

                q3Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q3Label.setForeground(new java.awt.Color(0, 0, 0));
                q3Label.setText("3. What does the fish have?");

                directionLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel3.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel3.setText("Direction: Describe the picture using the word");

                textArea3.setBackground(new java.awt.Color(153, 153, 153));
                textArea3.setColumns(20);
                textArea3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea3.setForeground(new java.awt.Color(0, 0, 0));
                textArea3.setRows(5);
                jScrollPane3.setViewportView(textArea3);
                textArea1.setEditable(false);

                clearButton3.setText("Clear");
                clearButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton3ActionPerformed(evt);
                        }
                });

                ReadButton3.setText("Read");
                ReadButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadButton3ActionPerformed(evt);
                        }
                });

                fishWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                fishWordButton3.setText("fish");
                fishWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fishWordButton3ActionPerformed(evt);
                        }
                });

                TheWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                TheWordButton3.setText("The");
                TheWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TheWordButton3ActionPerformed(evt);
                        }
                });

                bigWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                bigWordButton3.setText("big");
                bigWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bigWordButton3ActionPerformed(evt);
                        }
                });

                hasWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                hasWordButton3.setText("has");
                hasWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hasWordButton3ActionPerformed(evt);
                        }
                });

                nextButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton3.setText("Next");
                nextButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton3ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton3.setText("Sound");
                textToSpeechToggleButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton3ActionPerformed(evt);
                        }
                });

                finsWordButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                finsWordButton3.setText("fins");
                finsWordButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                finsWordButton3ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout q3PanelLayout = new javax.swing.GroupLayout(q3Panel);
                q3Panel.setLayout(q3PanelLayout);
                q3PanelLayout.setHorizontalGroup(
                        q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(q3Label)
                                                        .addComponent(directionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(q3PanelLayout.createSequentialGroup()
                                                                                        .addComponent(bigWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(hasWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(q3PanelLayout.createSequentialGroup()
                                                                                        .addComponent(fishWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(TheWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(clearButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(ReadButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 34, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q3PanelLayout.createSequentialGroup()
                                                .addGap(0, 667, Short.MAX_VALUE)
                                                .addComponent(textToSpeechToggleButton3))
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(nextButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(finsWordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                q3PanelLayout.setVerticalGroup(
                        q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q3PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textToSpeechToggleButton3)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(q3Label)
                                .addGap(18, 18, 18)
                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q3PanelLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(clearButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ReadButton3))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fishWordButton3)
                                        .addComponent(TheWordButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bigWordButton3)
                                        .addComponent(hasWordButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finsWordButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(nextButton3)
                                .addContainerGap())
                );

                assessmentTabbedPane.addTab("tab3", q3Panel);

                q4Panel.setBackground(new java.awt.Color(204, 204, 204));

                q4Label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q4Label.setForeground(new java.awt.Color(0, 0, 0));
                q4Label.setText("4. How many apples are there?");

                directionLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel4.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel4.setText("Direction: Describe the picture using the word");

                textArea4.setBackground(new java.awt.Color(153, 153, 153));
                textArea4.setColumns(20);
                textArea4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea4.setForeground(new java.awt.Color(0, 0, 0));
                textArea4.setRows(5);
                jScrollPane4.setViewportView(textArea4);
                textArea1.setEditable(false);

                clearButton4.setText("Clear");
                clearButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton4ActionPerformed(evt);
                        }
                });

                ReadButton4.setText("Read");
                ReadButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadButton4ActionPerformed(evt);
                        }
                });

                areWordButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                areWordButton4.setText("are");
                areWordButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                areWordButton4ActionPerformed(evt);
                        }
                });

                sixWordButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                sixWordButton4.setText("six");
                sixWordButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sixWordButton4ActionPerformed(evt);
                        }
                });

                applesWordButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                applesWordButton4.setText("apples");
                applesWordButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                applesWordButton4ActionPerformed(evt);
                        }
                });

                ThereWordButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                ThereWordButton4.setText("There");
                ThereWordButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ThereWordButton4ActionPerformed(evt);
                        }
                });

                nextButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton4.setText("Next");
                nextButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton4ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton4.setText("Sound");
                textToSpeechToggleButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton4ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout q4PanelLayout = new javax.swing.GroupLayout(q4Panel);
                q4Panel.setLayout(q4PanelLayout);
                q4PanelLayout.setHorizontalGroup(
                        q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(q4Label)
                                                        .addComponent(directionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(q4PanelLayout.createSequentialGroup()
                                                                                        .addComponent(areWordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(sixWordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                                                .addGap(239, 239, 239)
                                                                                .addComponent(applesWordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(ThereWordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(clearButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(ReadButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 34, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q4PanelLayout.createSequentialGroup()
                                                .addGap(0, 667, Short.MAX_VALUE)
                                                .addComponent(textToSpeechToggleButton4))
                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(nextButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                q4PanelLayout.setVerticalGroup(
                        q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q4PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textToSpeechToggleButton4)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(q4Label)
                                .addGap(18, 18, 18)
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q4PanelLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(clearButton4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ReadButton4))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sixWordButton4)
                                        .addComponent(areWordButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(applesWordButton4)
                                        .addComponent(ThereWordButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(nextButton4)
                                .addContainerGap())
                );

                assessmentTabbedPane.addTab("tab4", q4Panel);

                q5Panel.setBackground(new java.awt.Color(204, 204, 204));

                q4Label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                q4Label1.setForeground(new java.awt.Color(0, 0, 0));
                q4Label1.setText("5. What animal is on the box?");

                directionLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                directionLabel5.setForeground(new java.awt.Color(0, 0, 0));
                directionLabel5.setText("Direction: Describe the picture using the word");

                textArea5.setBackground(new java.awt.Color(153, 153, 153));
                textArea5.setColumns(20);
                textArea5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                textArea5.setForeground(new java.awt.Color(0, 0, 0));
                textArea5.setRows(5);
                jScrollPane5.setViewportView(textArea5);
                textArea1.setEditable(false);

                clearButton5.setText("Clear");
                clearButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButton5ActionPerformed(evt);
                        }
                });

                ReadButton5.setText("Read");
                ReadButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReadButton5ActionPerformed(evt);
                        }
                });

                boxWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                boxWordButton5.setText("box");
                boxWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                boxWordButton5ActionPerformed(evt);
                        }
                });

                isWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                isWordButton5.setText("is");
                isWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                isWordButton5ActionPerformed(evt);
                        }
                });

                TheWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                TheWordButton5.setText("The");
                TheWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TheWordButton5ActionPerformed(evt);
                        }
                });

                theWordButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                theWordButton5.setText("the");
                theWordButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                theWordButton5ActionPerformed(evt);
                        }
                });

                nextButton5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                nextButton5.setText("Next");
                nextButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButton5ActionPerformed(evt);
                        }
                });

                textToSpeechToggleButton5.setText("Sound");
                textToSpeechToggleButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textToSpeechToggleButton5ActionPerformed(evt);
                        }
                });

                catWordButton6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                catWordButton6.setText("cat");
                catWordButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                catWordButton6ActionPerformed(evt);
                        }
                });

                onWordButton6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                onWordButton6.setText("on");
                onWordButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                onWordButton6ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout q5PanelLayout = new javax.swing.GroupLayout(q5Panel);
                q5Panel.setLayout(q5PanelLayout);
                q5PanelLayout.setHorizontalGroup(
                        q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(q4Label1)
                                                        .addComponent(directionLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(q5PanelLayout.createSequentialGroup()
                                                                                        .addComponent(boxWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(isWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                                                .addGap(239, 239, 239)
                                                                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                                                                .addComponent(onWordButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(catWordButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                                                                .addComponent(TheWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(theWordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(clearButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(ReadButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 34, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q5PanelLayout.createSequentialGroup()
                                                .addGap(0, 667, Short.MAX_VALUE)
                                                .addComponent(textToSpeechToggleButton5))
                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(nextButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                q5PanelLayout.setVerticalGroup(
                        q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(q5PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textToSpeechToggleButton5)
                                .addGap(8, 8, 8)
                                .addComponent(directionLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(q4Label1)
                                .addGap(18, 18, 18)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(q5PanelLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(clearButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ReadButton5))
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(isWordButton5)
                                        .addComponent(boxWordButton5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TheWordButton5)
                                        .addComponent(theWordButton5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(onWordButton6)
                                        .addComponent(catWordButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(nextButton5)
                                .addContainerGap())
                );

                assessmentTabbedPane.addTab("tab5", q5Panel);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(assessmentTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(assessmentTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea1);
    }//GEN-LAST:event_clearButton1ActionPerformed

    private void readButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButton1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea1);
    }//GEN-LAST:event_readButton1ActionPerformed

    String[] q1Words = {"The", "net", "is", "wet"};
    String[] q2Words = {"The", "cat", "is", "on", "the", "mat"};
    String[] q3Words = {"The", "fish", "has", "big", "fins"};
    String[] q4Words = {"There", "are", "six", "apples"};
    String[] q5Words = {"The", "cat", "is", "on", "the", "box"};


    private void TheWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Append the word to the text area
        textArea1.append(q1Words[0] + " ");
        ButtonActions.speak(q1Words[0] + " ", textToSpeechToggleButton1);
    }

    private void wetWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wetWordButton1ActionPerformed
        // TODO add your handling code here:
        textArea1.append(q1Words[3] + " ");
        ButtonActions.speak(q1Words[3] + " ", textToSpeechToggleButton1);
    }//GEN-LAST:event_wetWordButton1ActionPerformed

    private void isWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWordButton1ActionPerformed
        // TODO add your handling code here:
        textArea1.append(q1Words[2] + " ");
        ButtonActions.speak(q1Words[2] + " ", textToSpeechToggleButton1);
    }//GEN-LAST:event_isWordButton1ActionPerformed

    private void netWordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netWordButton1ActionPerformed
        // TODO add your handling code here:
        textArea1.append(q1Words[1] + " ");
        ButtonActions.speak(q1Words[1] + " ", textToSpeechToggleButton1);
    }//GEN-LAST:event_netWordButton1ActionPerformed

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        // TODO add your handling code here:String correctAnswer = "The net is wet";
        String userAnswer = textArea1.getText().trim();
        ButtonActions.checkAnswerAndNext(q1Words, userAnswer, assessmentTabbedPane, textArea1);
    }//GEN-LAST:event_nextButton1ActionPerformed

    private void textToSpeechToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton1);
    }//GEN-LAST:event_textToSpeechToggleButton1ActionPerformed

    private void clearButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea2);
    }//GEN-LAST:event_clearButton2ActionPerformed

    private void ReadButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButton2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea2);
    }//GEN-LAST:event_ReadButton2ActionPerformed

    private void matWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[5] + " ");
        ButtonActions.speak(q2Words[5] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_matWordButton2ActionPerformed

    private void TheWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[0] + " ");
        ButtonActions.speak(q2Words[0] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_TheWordButton2ActionPerformed

    private void isWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[2] + " ");
        ButtonActions.speak(q2Words[2] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_isWordButton2ActionPerformed

    private void onWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[3] + " ");
        ButtonActions.speak(q2Words[3] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_onWordButton2ActionPerformed

    private void nextButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton2ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textArea2.getText().trim();
        ButtonActions.checkAnswerAndNext(q2Words, userAnswer, assessmentTabbedPane, textArea2);
    }//GEN-LAST:event_nextButton2ActionPerformed

    private void textToSpeechToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton2);
    }//GEN-LAST:event_textToSpeechToggleButton2ActionPerformed

    private void catWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[1] + " ");
        ButtonActions.speak(q2Words[1] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_catWordButton2ActionPerformed

    private void theWordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theWordButton2ActionPerformed
        // TODO add your handling code here:
        textArea2.append(q2Words[4] + " ");
        ButtonActions.speak(q2Words[4] + " ", textToSpeechToggleButton2);
    }//GEN-LAST:event_theWordButton2ActionPerformed

    private void clearButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea3);
    }//GEN-LAST:event_clearButton3ActionPerformed

    private void ReadButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButton3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea3);
    }//GEN-LAST:event_ReadButton3ActionPerformed

    private void fishWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[1] + " ");
        ButtonActions.speak(q3Words[1] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_fishWordButton3ActionPerformed

    private void TheWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[0] + " ");
        ButtonActions.speak(q3Words[0] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_TheWordButton3ActionPerformed

    private void bigWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[3] + " ");
        ButtonActions.speak(q3Words[3] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_bigWordButton3ActionPerformed

    private void hasWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[2] + " ");
        ButtonActions.speak(q3Words[2] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_hasWordButton3ActionPerformed

    private void nextButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton3ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textArea3.getText().trim();
        ButtonActions.checkAnswerAndNext(q3Words, userAnswer, assessmentTabbedPane, textArea3);
    }//GEN-LAST:event_nextButton3ActionPerformed

    private void textToSpeechToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton3ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton3);
    }//GEN-LAST:event_textToSpeechToggleButton3ActionPerformed

    private void finsWordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finsWordButton3ActionPerformed
        // TODO add your handling code here:
        textArea3.append(q3Words[4] + " ");
        ButtonActions.speak(q3Words[4] + " ", textToSpeechToggleButton3);
    }//GEN-LAST:event_finsWordButton3ActionPerformed

    private void clearButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textArea4);
    }//GEN-LAST:event_clearButton4ActionPerformed

    private void ReadButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButton4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textArea4);
    }//GEN-LAST:event_ReadButton4ActionPerformed

    private void areWordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areWordButton4ActionPerformed
        // TODO add your handling code here:
        textArea4.append(q4Words[1] + " ");
        ButtonActions.speak(q4Words[1] + " ", textToSpeechToggleButton4);
    }//GEN-LAST:event_areWordButton4ActionPerformed

    private void sixWordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixWordButton4ActionPerformed
        // TODO add your handling code here:
        textArea4.append(q4Words[2] + " ");
        ButtonActions.speak(q4Words[2] + " ", textToSpeechToggleButton4);
    }//GEN-LAST:event_sixWordButton4ActionPerformed

    private void applesWordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applesWordButton4ActionPerformed
        // TODO add your handling code here:
        textArea4.append(q4Words[3] + " ");
        ButtonActions.speak(q4Words[3] + " ", textToSpeechToggleButton4);
    }//GEN-LAST:event_applesWordButton4ActionPerformed

    private void ThereWordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThereWordButton4ActionPerformed
        // TODO add your handling code here:
        textArea4.append(q4Words[0] + " ");
        ButtonActions.speak(q4Words[0] + " ", textToSpeechToggleButton4);
    }//GEN-LAST:event_ThereWordButton4ActionPerformed

    private void nextButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton4ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textArea4.getText().trim();
        ButtonActions.checkAnswerAndNext(q4Words, userAnswer, assessmentTabbedPane, textArea4);
    }//GEN-LAST:event_nextButton4ActionPerformed

    private void textToSpeechToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton4ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(textToSpeechToggleButton4);
    }//GEN-LAST:event_textToSpeechToggleButton4ActionPerformed

        private void clearButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_clearButton5ActionPerformed

        private void ReadButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_ReadButton5ActionPerformed

        private void boxWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxWordButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_boxWordButton5ActionPerformed

        private void isWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWordButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_isWordButton5ActionPerformed

        private void TheWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheWordButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_TheWordButton5ActionPerformed

        private void theWordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theWordButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_theWordButton5ActionPerformed

        private void nextButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_nextButton5ActionPerformed

        private void textToSpeechToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToSpeechToggleButton5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_textToSpeechToggleButton5ActionPerformed

        private void catWordButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catWordButton6ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_catWordButton6ActionPerformed

        private void onWordButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onWordButton6ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_onWordButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assessment().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton ReadButton2;
        private javax.swing.JButton ReadButton3;
        private javax.swing.JButton ReadButton4;
        private javax.swing.JButton ReadButton5;
        private javax.swing.JButton TheWordButton1;
        private javax.swing.JButton TheWordButton2;
        private javax.swing.JButton TheWordButton3;
        private javax.swing.JButton TheWordButton5;
        private javax.swing.JButton ThereWordButton4;
        private javax.swing.JButton applesWordButton4;
        private javax.swing.JButton areWordButton4;
        private javax.swing.JTabbedPane assessmentTabbedPane;
        private javax.swing.JButton bigWordButton3;
        private javax.swing.JButton boxWordButton5;
        private javax.swing.JButton catWordButton2;
        private javax.swing.JButton catWordButton6;
        private javax.swing.JButton clearButton1;
        private javax.swing.JButton clearButton2;
        private javax.swing.JButton clearButton3;
        private javax.swing.JButton clearButton4;
        private javax.swing.JButton clearButton5;
        private javax.swing.JLabel directionLabel;
        private javax.swing.JLabel directionLabel2;
        private javax.swing.JLabel directionLabel3;
        private javax.swing.JLabel directionLabel4;
        private javax.swing.JLabel directionLabel5;
        private javax.swing.JButton finsWordButton3;
        private javax.swing.JButton fishWordButton3;
        private javax.swing.JButton hasWordButton3;
        private javax.swing.JButton isWordButton1;
        private javax.swing.JButton isWordButton2;
        private javax.swing.JButton isWordButton5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JButton matWordButton2;
        private javax.swing.JButton netWordButton1;
        private javax.swing.JButton nextButton1;
        private javax.swing.JButton nextButton2;
        private javax.swing.JButton nextButton3;
        private javax.swing.JButton nextButton4;
        private javax.swing.JButton nextButton5;
        private javax.swing.JButton onWordButton2;
        private javax.swing.JButton onWordButton6;
        private javax.swing.JLabel q1Label;
        private javax.swing.JPanel q1Panel;
        private javax.swing.JLabel q2Label;
        private javax.swing.JPanel q2Panel;
        private javax.swing.JLabel q3Label;
        private javax.swing.JPanel q3Panel;
        private javax.swing.JLabel q4Label;
        private javax.swing.JLabel q4Label1;
        private javax.swing.JPanel q4Panel;
        private javax.swing.JPanel q5Panel;
        private javax.swing.JButton readButton1;
        private javax.swing.JButton sixWordButton4;
        private javax.swing.JTextArea textArea1;
        private javax.swing.JTextArea textArea2;
        private javax.swing.JTextArea textArea3;
        private javax.swing.JTextArea textArea4;
        private javax.swing.JTextArea textArea5;
        private javax.swing.JToggleButton textToSpeechToggleButton1;
        private javax.swing.JToggleButton textToSpeechToggleButton2;
        private javax.swing.JToggleButton textToSpeechToggleButton3;
        private javax.swing.JToggleButton textToSpeechToggleButton4;
        private javax.swing.JToggleButton textToSpeechToggleButton5;
        private javax.swing.JButton theWordButton2;
        private javax.swing.JButton theWordButton5;
        private javax.swing.JButton wetWordButton1;
        // End of variables declaration//GEN-END:variables
}