/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Core.AssessmentPage.TakeChallengeModeOfDifficulty;

import Core.Actions.ButtonActions;
import Core.AssessmentPage.TakeChallengeAssessment;

/**
 * @author Marc
 */
public class HardTakeChallenge extends javax.swing.JFrame {

    /**
     * Creates new form HardTakeChallenge
     */
    public HardTakeChallenge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                HTakeChallengeJTabbedPane = new javax.swing.JTabbedPane();
                TCtabbedPane1H = new javax.swing.JPanel();
                instructionLabelTC1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                readButtonH1 = new javax.swing.JButton();
                clearButtonH1 = new javax.swing.JButton();
                hintButtonH1 = new javax.swing.JButton();
                AButtonH1 = new javax.swing.JButton();
                PButtonH1 = new javax.swing.JButton();
                LButtonH1 = new javax.swing.JButton();
                EButtonH1 = new javax.swing.JButton();
                nextButtonH1 = new javax.swing.JButton();
                TButtonH1 = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                textAreaH1 = new javax.swing.JTextArea();
                jPanel3 = new javax.swing.JPanel();
                soundToggleButtonH1 = new javax.swing.JToggleButton();
                returnButtonH1 = new javax.swing.JButton();
                E2ButtonH2 = new javax.swing.JButton();
                NButtonH3 = new javax.swing.JButton();
                HButtonH1 = new javax.swing.JButton();
                TCtabbedPane1H1 = new javax.swing.JPanel();
                instructionLabelTC2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                readButtonH2 = new javax.swing.JButton();
                clearButtonH2 = new javax.swing.JButton();
                hintButtonH2 = new javax.swing.JButton();
                F2ButtonH2 = new javax.swing.JButton();
                IButtonH2 = new javax.swing.JButton();
                EButtonH2 = new javax.swing.JButton();
                RButtonH2 = new javax.swing.JButton();
                nextButtonH2 = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                textAreaH2 = new javax.swing.JTextArea();
                jPanel4 = new javax.swing.JPanel();
                soundToggleButtonH2 = new javax.swing.JToggleButton();
                F1ButtonH2 = new javax.swing.JButton();
                GButtonH2 = new javax.swing.JButton();
                AButtonH2 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                TCtabbedPane1H.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane1H.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC1.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC1.setText("Guess the Word");
                TCtabbedPane1H.add(instructionLabelTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane1H.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonH1.setText("Read");
                readButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(readButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonH1.setText("Clear");
                clearButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(clearButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonH1.setText("Hint");
                TCtabbedPane1H.add(hintButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                AButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonH1.setText("A");
                AButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(AButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 98, 67));

                PButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                PButtonH1.setText("P");
                PButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(PButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 98, 67));

                LButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                LButtonH1.setText("L");
                LButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(LButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 98, 67));

                EButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonH1.setText("E");
                EButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(EButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 98, 67));

                nextButtonH1.setText("Next");
                nextButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(nextButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                TButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                TButtonH1.setText("T");
                TButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(TButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 98, 67));

                textAreaH1.setEditable(false);
                textAreaH1.setColumns(20);
                textAreaH1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaH1.setRows(5);
                jScrollPane1.setViewportView(textAreaH1);

                TCtabbedPane1H.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 220, 70));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 320, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 180, Short.MAX_VALUE)
                );

                TCtabbedPane1H.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 320, 180));

                soundToggleButtonH1.setText("Sound");
                soundToggleButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(soundToggleButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                returnButtonH1.setText("Return");
                returnButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(returnButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 485, 73, -1));

                E2ButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                E2ButtonH2.setText("E");
                E2ButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                E2ButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(E2ButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 98, 67));

                NButtonH3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                NButtonH3.setText("N");
                NButtonH3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                NButtonH3ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(NButtonH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 98, 67));

                HButtonH1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                HButtonH1.setText("H");
                HButtonH1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                HButtonH1ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H.add(HButtonH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 98, 67));

                HTakeChallengeJTabbedPane.addTab("tab1", TCtabbedPane1H);

                TCtabbedPane1H1.setBackground(new java.awt.Color(204, 204, 204));
                TCtabbedPane1H1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                instructionLabelTC2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
                instructionLabelTC2.setForeground(new java.awt.Color(0, 0, 0));
                instructionLabelTC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                instructionLabelTC2.setText("Guess the Word");
                TCtabbedPane1H1.add(instructionLabelTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 531, 80));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                TCtabbedPane1H1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

                readButtonH2.setText("Read");
                readButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(readButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 435, 73, -1));

                clearButtonH2.setText("Clear");
                clearButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(clearButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 435, 73, -1));

                hintButtonH2.setText("Hint");
                TCtabbedPane1H1.add(hintButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 435, 73, -1));

                F2ButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                F2ButtonH2.setText("F");
                F2ButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                F2ButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(F2ButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 98, 67));

                IButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                IButtonH2.setText("I");
                IButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                IButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(IButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 98, 67));

                EButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                EButtonH2.setText("E");
                EButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(EButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 98, 67));

                RButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                RButtonH2.setText("R");
                RButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(RButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 98, 67));

                nextButtonH2.setText("Next");
                nextButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(nextButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 73, -1));

                textAreaH2.setEditable(false);
                textAreaH2.setColumns(20);
                textAreaH2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                textAreaH2.setRows(5);
                jScrollPane2.setViewportView(textAreaH2);

                TCtabbedPane1H1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 220, 70));

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 320, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 180, Short.MAX_VALUE)
                );

                TCtabbedPane1H1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 320, 180));

                soundToggleButtonH2.setText("Sound");
                soundToggleButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                soundToggleButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(soundToggleButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

                F1ButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                F1ButtonH2.setText("F");
                F1ButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                F1ButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(F1ButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 98, 67));

                GButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                GButtonH2.setText("G");
                GButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(GButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 98, 67));

                AButtonH2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                AButtonH2.setText("A");
                AButtonH2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AButtonH2ActionPerformed(evt);
                        }
                });
                TCtabbedPane1H1.add(AButtonH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 98, 67));

                HTakeChallengeJTabbedPane.addTab("tab2", TCtabbedPane1H1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 800, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(HTakeChallengeJTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 548, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(HTakeChallengeJTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    String[] wordH1 = {"E", "L", "E", "P", "H", "A", "N", "T"};
    String[] wordH2 = {"G", "I", "R", "A", "F", "F", "E"};
    String[] wordH3 = {"G", "L", "A", "S", "S", "E", "S"};
    String[] wordH4 = {"C", "A", "M", "E", "R", "A"};
    String[] wordH5 = {"K", "A", "N", "G", "A", "R", "O", "O"};

    private void readButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH1);
    }//GEN-LAST:event_readButtonH1ActionPerformed

    private void clearButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH1);
    }//GEN-LAST:event_clearButtonH1ActionPerformed

    private void AButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[5]);
        ButtonActions.speak(wordH1[5], soundToggleButtonH1);
    }//GEN-LAST:event_AButtonH1ActionPerformed

    private void PButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[3]);
        ButtonActions.speak(wordH1[3], soundToggleButtonH1);
    }//GEN-LAST:event_PButtonH1ActionPerformed

    private void LButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[1]);
        ButtonActions.speak(wordH1[1], soundToggleButtonH1);
    }//GEN-LAST:event_LButtonH1ActionPerformed

    private void EButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[0]);
        ButtonActions.speak(wordH1[0], soundToggleButtonH1);
    }//GEN-LAST:event_EButtonH1ActionPerformed

    private void nextButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonH1ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaH1.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH1, userAnswer, HTakeChallengeJTabbedPane, textAreaH1, false);
    }//GEN-LAST:event_nextButtonH1ActionPerformed

    private void TButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[7]);
        ButtonActions.speak(wordH1[7], soundToggleButtonH1);
    }//GEN-LAST:event_TButtonH1ActionPerformed

    private void soundToggleButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH1ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH1);
    }//GEN-LAST:event_soundToggleButtonH1ActionPerformed

    private void returnButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonH1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TakeChallengeAssessment().setVisible(true);
    }//GEN-LAST:event_returnButtonH1ActionPerformed

    private void E2ButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[2]);
        ButtonActions.speak(wordH1[2], soundToggleButtonH1);
    }//GEN-LAST:event_E2ButtonH2ActionPerformed

    private void NButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NButtonH3ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[6]);
        ButtonActions.speak(wordH1[6], soundToggleButtonH1);
    }//GEN-LAST:event_NButtonH3ActionPerformed

    private void HButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HButtonH1ActionPerformed
        // TODO add your handling code here:
        textAreaH1.append(wordH1[4]);
        ButtonActions.speak(wordH1[4], soundToggleButtonH1);
    }//GEN-LAST:event_HButtonH1ActionPerformed

    private void readButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.readText(textAreaH2);
    }//GEN-LAST:event_readButtonH2ActionPerformed

    private void clearButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.clearTextArea(textAreaH2);
    }//GEN-LAST:event_clearButtonH2ActionPerformed

    private void F2ButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[5]);
        ButtonActions.speak(wordH2[5], soundToggleButtonH2);
    }//GEN-LAST:event_F2ButtonH2ActionPerformed

    private void IButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[1]);
        ButtonActions.speak(wordH2[1], soundToggleButtonH2);
    }//GEN-LAST:event_PButtonH2ActionPerformed

    private void EButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[6]);
        ButtonActions.speak(wordH2[6], soundToggleButtonH2);
    }//GEN-LAST:event_EButtonH2ActionPerformed

    private void RButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[2]);
        ButtonActions.speak(wordH2[2], soundToggleButtonH2);
    }//GEN-LAST:event_RButtonH2ActionPerformed

    private void nextButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonH2ActionPerformed
        // TODO add your handling code here:
        String userAnswer = textAreaH2.getText().trim();
        ButtonActions.checkAnswerAndNext(wordH2, userAnswer, HTakeChallengeJTabbedPane, textAreaH2, false);
    }//GEN-LAST:event_nextButtonH2ActionPerformed

    private void soundToggleButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundToggleButtonH2ActionPerformed
        // TODO add your handling code here:
        ButtonActions.toggleTextToSpeech(soundToggleButtonH2);
    }//GEN-LAST:event_soundToggleButtonH2ActionPerformed

    private void F1ButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[4]);
        ButtonActions.speak(wordH2[4], soundToggleButtonH2);
    }//GEN-LAST:event_F1ButtonH2ActionPerformed

    private void GButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[0]);
        ButtonActions.speak(wordH2[0], soundToggleButtonH2);
    }//GEN-LAST:event_GButtonH2ActionPerformed

    private void AButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonH2ActionPerformed
        // TODO add your handling code here:
        textAreaH2.append(wordH2[3]);
        ButtonActions.speak(wordH2[3], soundToggleButtonH2);
    }//GEN-LAST:event_AButtonH2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HardTakeChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HardTakeChallenge().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton AButtonH1;
        private javax.swing.JButton AButtonH2;
        private javax.swing.JButton E2ButtonH2;
        private javax.swing.JButton EButtonH1;
        private javax.swing.JButton EButtonH2;
        private javax.swing.JButton F1ButtonH2;
        private javax.swing.JButton F2ButtonH2;
        private javax.swing.JButton GButtonH2;
        private javax.swing.JButton HButtonH1;
        private javax.swing.JTabbedPane HTakeChallengeJTabbedPane;
        private javax.swing.JButton IButtonH2;
        private javax.swing.JButton LButtonH1;
        private javax.swing.JButton NButtonH3;
        private javax.swing.JButton PButtonH1;
        private javax.swing.JButton RButtonH2;
        private javax.swing.JButton TButtonH1;
        private javax.swing.JPanel TCtabbedPane1H;
        private javax.swing.JPanel TCtabbedPane1H1;
        private javax.swing.JButton clearButtonH1;
        private javax.swing.JButton clearButtonH2;
        private javax.swing.JButton hintButtonH1;
        private javax.swing.JButton hintButtonH2;
        private javax.swing.JLabel instructionLabelTC1;
        private javax.swing.JLabel instructionLabelTC2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JButton nextButtonH1;
        private javax.swing.JButton nextButtonH2;
        private javax.swing.JButton readButtonH1;
        private javax.swing.JButton readButtonH2;
        private javax.swing.JButton returnButtonH1;
        private javax.swing.JToggleButton soundToggleButtonH1;
        private javax.swing.JToggleButton soundToggleButtonH2;
        private javax.swing.JTextArea textAreaH1;
        private javax.swing.JTextArea textAreaH2;
        // End of variables declaration//GEN-END:variables
}
